### PR TITLE
Migrating Cisco switch in R4-PA-C02 to the dell switch in R4-PA-C02

### PR DESCRIPTION
**Pull request by hakasapl**
This is copying the switch config that is on the existing cisco into our yaml format. Let me know if anything looks off. There's a bunch of settings for native vlans in the trunk. This config doesn't preserve that but as long as the port is tagging on the other end that shouldn't be an issue. That's something I'll add later. Here is the config from the cisco switch:

I didn't copy the configs for the vlan interfaces yet - let me know which of those are still needed. I also only copied the interface configs for the interfaces that are currently up

```
!Command: show running-config interface
!Time: Fri Jul 12 17:15:07 2024

version 7.3(11)N1(1)

interface Vlan1

interface Vlan3
  description "VPC Keepalive Link to SFAGGR-MGH-PODB-R3C19-1"
  no shutdown
  no ip redirects
  ip address 10.2.29.113/30

interface Vlan127
  no shutdown
  no ip redirects
  ip address 129.10.5.2/24
  ip ospf passive-interface
  ip router ospf 1 area 0.3.0.5
  vrrp 13
    priority 110
    address 129.10.5.1
    no shutdown
    exit

interface Vlan150
  no shutdown
  no ip redirects
  ip address 10.2.29.126/30
  ip router ospf 1 area 0.3.0.5

interface Vlan204

interface Vlan250
  no shutdown
  no ip redirects
  ip address 192.168.24.2/24
  ip ospf passive-interface
  vrrp 10
    priority 110
    address 192.168.24.1
    no shutdown
    exit

interface Vlan251
  description "P2P Connection between MOC-NEU-PODB-R3C19-1 to MOC-NEU-PODB-R3C17-1"
  no shutdown
  mtu 9216
  no ip redirects
  ip address 10.2.29.121/30
  ip router ospf 1 area 0.3.0.5

interface Vlan930
  no shutdown
  ip address 10.80.2.102/20

interface Vlan3800
  no shutdown
  no ip redirects
  ip address 192.168.192.11/24

interface Ethernet1/1
  description "Kaizen Compute"
  switchport access vlan 249

interface Ethernet1/2
  description "Kaizen Compute"
  switchport mode trunk
  switchport trunk native vlan 277
  switchport trunk allowed vlan 201,250,277
  spanning-tree port type edge trunk

interface Ethernet1/3
  description "Kaizen Compute"
  switchport access vlan 249

interface Ethernet1/4
  description "Kaizen Compute"
  switchport mode trunk
  switchport trunk native vlan 277
  switchport trunk allowed vlan 201,250,277
  spanning-tree port type edge trunk

interface Ethernet1/5
  description "Kaizen Compute"
  switchport access vlan 249

interface Ethernet1/6
  description "Kaizen Compute"
  switchport mode trunk
  switchport trunk native vlan 277
  switchport trunk allowed vlan 201,250,277
  spanning-tree port type edge trunk

interface Ethernet1/7
  description "Kaizen Compute"
  switchport access vlan 249

interface Ethernet1/8
  description "Kaizen Compute"
  switchport mode trunk
  switchport trunk native vlan 277
  switchport trunk allowed vlan 201,250,277
  spanning-tree port type edge trunk

interface Ethernet1/9
  description "Kaizen Compute"
  switchport access vlan 249

interface Ethernet1/10
  description "Kaizen Compute"
  switchport mode trunk
  switchport trunk native vlan 277
  switchport trunk allowed vlan 201,250,277
  spanning-tree port type edge trunk

interface Ethernet1/11
  description "Mass computing Cluster CISCO"
  switchport access vlan 250

interface Ethernet1/12
  description "Mass computing Cluster CISCO"
  switchport access vlan 277

interface Ethernet1/13
  description "Mass computing Cluster CISCO"
  switchport mode trunk
  switchport trunk native vlan 201
  switchport trunk allowed vlan 201,250,1004

interface Ethernet1/14
  description "Mass computing Cluster CISCO"
  switchport mode trunk
  switchport trunk native vlan 201
  switchport trunk allowed vlan 201,250,1004

interface Ethernet1/15
  switchport mode trunk

interface Ethernet1/16
  switchport mode trunk
  switchport trunk native vlan 127

interface Ethernet1/17
  description "Mass computing Cluster CISCO"
  switchport mode trunk

interface Ethernet1/18
  description "Mass computing Cluster CISCO"
  switchport mode trunk
  switchport trunk native vlan 127

interface Ethernet1/19
  description "Mass computing Cluster CISCO"
  switchport mode trunk
  switchport trunk native vlan 315
  switchport trunk allowed vlan 315
  spanning-tree port type edge trunk

interface Ethernet1/20
  description "Mass computing Cluster CISCO"
  switchport mode trunk
  switchport trunk native vlan 500
  switchport trunk allowed vlan 500
  spanning-tree port type edge trunk

interface Ethernet1/21
  description "Kaizen Network Controller 2"
  switchport mode trunk

interface Ethernet1/22
  description "Kaizen Network Controller 2"
  switchport mode trunk

interface Ethernet1/23
  description "Kaizen GPU2 compute"
  switchport mode trunk
  switchport trunk native vlan 4093
  switchport trunk allowed vlan none
  spanning-tree port type edge trunk

interface Ethernet1/24
  description "Kaizen GPU2 compute"
  switchport mode trunk
  switchport trunk native vlan 277
  switchport trunk allowed vlan 277
  spanning-tree port type edge trunk

interface Ethernet1/25
  switchport mode trunk
  switchport trunk native vlan 930

interface Ethernet1/26
  switchport mode trunk
  switchport trunk native vlan 930

interface Ethernet1/27
  description oct-41-1
  switchport access vlan 204

interface Ethernet1/28
  description oct-41-2
  no switchport

interface Ethernet1/29
  description oct-43-1
  switchport access vlan 204

interface Ethernet1/30
  description oct-43-2
  no switchport

interface Ethernet1/31
  description oct-45-1
  switchport access vlan 204

interface Ethernet1/32
  description oct-45-2
  no switchport

interface Ethernet1/33
  description "Fujitsu 17-17 nic1"
  switchport access vlan 930
  speed 1000

interface Ethernet1/34
  description "OSD2 nic2"
  switchport access vlan 930
  speed 1000

interface Ethernet1/35
  switchport access vlan 930
  speed 1000

interface Ethernet1/36
  switchport access vlan 930
  speed 1000

interface Ethernet1/37
  switchport access vlan 999
  spanning-tree port type edge trunk

interface Ethernet1/38
  switchport access vlan 999
  spanning-tree port type edge trunk

interface Ethernet1/39
  switchport access vlan 999
  spanning-tree port type edge trunk

interface Ethernet1/40
  switchport access vlan 999
  spanning-tree port type edge trunk

interface Ethernet1/41
  description "Keepalive Link SFAGGR-MGH-PODA-R3C19-1 1/41"
  switchport mode trunk

interface Ethernet1/42
  description "Keepalive Link SFAGGR-MGH-PODA-R3C19-1 1/42"
  switchport mode trunk

interface Ethernet1/43
  switchport mode trunk

interface Ethernet1/44
  switchport mode trunk

interface Ethernet1/45
  switchport access vlan 999

interface Ethernet1/46
  switchport access vlan 999

interface Ethernet1/47
  switchport access vlan 930

interface Ethernet1/48
  description "port-channel to SFCORE-MGH-MDA-R6C23-1 eth2/5"
  switchport mode trunk
  switchport trunk allowed vlan 150,3800,3802

interface Ethernet2/1
  description "cache-server-17-41-nic2"
  switchport mode trunk
  switchport trunk native vlan 204
  switchport trunk allowed vlan 204,267,280

interface Ethernet2/2
  description "cache-server-17-41-nic1"
  switchport mode trunk
  switchport trunk native vlan 277
  switchport trunk allowed vlan 252,277,306,625

interface Ethernet2/3
  description NFS/DRBD server
  switchport mode trunk
  switchport trunk native vlan 201

interface Ethernet2/4
  description temp-to-other-cisco
  switchport mode trunk

interface Ethernet2/5
  no lldp transmit
  no lldp receive
  switchport mode trunk
  switchport trunk native vlan 201

interface Ethernet2/6
  switchport mode trunk

interface mgmt0
  vrf member management
  ip address 10.0.17.42/19

interface loopback0
  ip address 10.2.2.1/32
  ip ospf advertise-subnet
  ip router ospf 1 area 0.3.0.5
```

### CODE REVIEW

**Comment by naved001** [comment]
vlan interface 127 is the neu public network, are we directly going to migrate that to the firewall or do we want to configure this dell switch?

**Comment by naved001** [comment]
it looks like both of the cisco switches connect to NEU switches (see port 48 and/or check lldp neighbors). Although I am not sure which one actually brings us vlan 127 (1 or both).

**Comment by hakasapl** [comment]
@naved001 you're right. Dell os9 supports OSPF so I think we should plan to move these links to the dell switches in the rack. I will need to figure out what the config should look like on the dells and then we can disconnect one of them without downtime because they are a VRRP pair, we'll then have the dell switch join the VRRP pair and then remove the other one. If we plan this out we should be able to do it with no downtime, and a pretty easy fallback plan of just plugging it back into the Ciscos

**Comment by naved001** [comment]
@hakasapl do we need to keep NEU in loop for this switch or it doesn't matter to them what we have on our end?

**Comment by hakasapl** [comment]
> @hakasapl do we need to keep NEU in loop for this switch or it doesn't matter to them what we have on our end?

We should let them know what we plan to do and when but they shouldn't need to be involved in the actual operation, it should be all on our end

**Comment by joachimweyl** [comment]
@hakasapl do we have a date we plan to merge this?

**Comment by hakasapl** [comment]
We are still in talks with NEU about this so this should stay open for now

**Pull request merged**
